services:
  backend_1:
    # build: ../
    image: nepiskopos/appimg
    environment:
      - PORT=8000
    networks:
      loadbalancing:
        ipv4_address: 192.168.0.3
  backend_2:
    # build: ../
    image: nepiskopos/appimg
    environment:
      - PORT=8000
    networks:
      loadbalancing:
        ipv4_address: 192.168.0.4
  backend_3:
    # build: ../
    image: nepiskopos/appimg
    environment:
      - PORT=8000
    networks:
      loadbalancing:
        ipv4_address: 192.168.0.5
  backend_4:
    # build: ../
    image: nepiskopos/appimg
    environment:
      - PORT=8000
    networks:
      loadbalancing:
        ipv4_address: 192.168.0.6

  nginx:
    build: ./
    ports:
      - "80:80"
    networks:
      loadbalancing:
        ipv4_address: 192.168.0.2
    depends_on:
      - backend_1
      - backend_2
      - backend_3
      - backend_4
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://192.168.0.3:8000 || http://192.168.0.4:8000 || http://192.168.0.5:8000 || http://192.168.0.6:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  loadbalancing:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
